version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: peopostore_db
    environment:
      MYSQL_ROOT_PASSWORD: Root@password123
      MYSQL_DATABASE: peopostore
    ports:
      - '3306:3306'
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    networks:
      - peopostore_net

  backend:
    container_name: peopostore_api
    image: longbp1606/peopostore_api:latest
    build:
      context: ./peopo-store-be
      dockerfile: Dockerfile
    env_file:
      - ./.env.be
    ports:
      - '3000:3000'
    restart: always
    networks:
      - peopostore_net

  frontend:
    container_name: peopostore_fe
    image: longbp1606/peopostore_fe:latest
    build: 
      context: ./peopo-store-fe
      dockerfile: Dockerfile
    env_file:
      - ./.env.fe
    ports:
      - 5173:80
    restart: always
    networks:
      - peopostore_net

networks:
  aphromas_net:
    driver: bridge

volumes:
  db_vol: 
